#!/bin/sh

if [ $LOG_LEVEL ]; then
  sed -i -E s/^level=.+$/level=$LOG_LEVEL/ $LOG_CONF_FILE
fi

sed -i s/^las_url\ =\ .*/las_url\ =\ http:\\/\\/$IP_BACKEND_LAS:$PORT_BACKEND_LAS\\/las\\/analyze/ "$CONF_FILE"

/usr/bin/gunicorn $GUNICORN_RELOAD -w $GUNICORN_WORKER_AMOUNT -t $GUNICORN_TIMEOUT -b 0.0.0.0:5000 run:app